name: App with Github Actions, ArgoCD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Create application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties

    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml

    - name: Rename JAR file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check JAR file
      run: ls ./target

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./target/*.jar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Checkout ArgoCD manifest repository
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.G_USER }}/${{ secrets.G_REPOSITORY }}
        ref: main
        token: ${{ secrets.G_TOKEN }}

    - name: Update application image in eks-app.yaml
      run: |
        sed -i "s%image: ${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:[a-zA-Z0-9._-]*%image: ${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}%" ./manifest/eks-app.yaml
        sed -i "s%image: [0-9]\{12,\}\.dkr\.ecr\.[a-z0-9-]\+\.amazonaws\.com/[a-zA-Z0-9._-]\+:[a-zA-Z0-9._-]*%image: ${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}%" ./manifest/eks-app.yaml

    - name: Commit and push changes if needed
      run: |
        git config --local user.email "madsenss@naver.com"
        git config --local user.name "madsensss"

        if git diff --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        git add ./manifest/eks-app.yaml
        git commit -m "Update application image version for ArgoCD"
        git pull --rebase origin main
        git push origin main
